# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599bdc708eaa14137c5a48e7195831490afe4f2839206c83e796be9c754191d95b6be4dd20006becc9d3d78e3ae874bb3c60bb2696bdcc4383c5806c1fdd77d3

test:
  secret_key_base: 7f71c88e81884959dbf628071c0238b1f3466740929dc44b707af1ca55a84069b397fc8b8d3e160042f6d283719e6f375ac971be324378b91f61235df56d8396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
